### ISSUE TITLE
Healthbot crashes when I say I haven't volunteered

### ISSUE THREAD

**Issue by Greyuwi** [CDCgov/covid19healthbot#22] opened 2020-07-15 20:19 UTC
When I answer the question, "In the last two weeks, have you worked or volunteered in a healthcare facility or as a first responder?" the bot crashes with "Oops. Something went wrong and we need to start over." This happened multiple times. I've only tried it with the instance hosted here: https://covid19healthbot.cdc.gov/

I've pasted my interaction below. Thank you.

----------------------------------------

The purpose of the Coronavirus Self-Checker is to help you make decisions about seeking appropriate medical care. This system is not intended for the diagnosis or treatment of disease or other conditions, including COVID-19. This system is intended only for adults who are 18 years and older and currently located in the United States.

This project was made possible through a partnership with the CDC Foundation and is enabled by Microsoft’s Azure platform. CDC’s collaboration with a non-federal organization does not imply an endorsement of any one particular service, product, or enterprise.

ᵥₑᵣ₆₂ ₍₂₀₂₀₋₀₇₋₁₅₎

Bot sent

I agree

I don't agree
Sent at July 15 at 4:07 PM2 minutes ago
User You said, I agree . Sent at July 15 at 4:07 PM.
I agree
I agree

Sent at July 15 at 4:07 PM2 minutes ago
Bot CDC said, Hi, I’m Clara. I’m going to ask you some questions. I will use your answers to give you advice about the right level of medical care you should seek. But first, if you are experiencing a life-threatening emergency, please call 911 immediately. If you are not experiencing a life-threatening emergency, let’s get started. . Sent at July 15 at 4:07 PM.
CDC

Hi, I’m Clara. I’m going to ask you some questions. I will use your answers to give you advice about the right level of medical care you should seek. But first, if you are experiencing a life-threatening emergency, please call 911 immediately. If you are not experiencing a life-threatening emergency, let’s get started.
Hi, I’m Clara. I’m going to ask you some questions. I will use your answers to give you advice about the right level of medical care you should seek.

But first, if you are experiencing a life-threatening emergency, please call 911 immediately.

If you are not experiencing a life-threatening emergency, let’s get started.

Bot CDC said, During the assessment, you can refresh the page if you need to start again. . Sent at July 15 at 4:07 PM.
CDC

During the assessment, you can refresh the page if you need to start again.
During the assessment, you can refresh the page if you need to start again.

Bot CDC said, Are you in the United States right now? . Sent at July 15 at 4:07 PM.
CDC

Are you in the United States right now?
Are you in the United States right now?

Bot sent

Yes

No
Sent at July 15 at 4:07 PM2 minutes ago
User You said, Yes . Sent at July 15 at 4:08 PM.
Yes
Yes

Sent at July 15 at 4:08 PM2 minutes ago
Bot CDC said, Where in the United States are you located? . Sent at July 15 at 4:08 PM.
CDC

Where in the United States are you located?
Where in the United States are you located?

Bot sent

M[Redacted]

Submit
Bot CDC said, Are you answering for yourself or someone else? . Sent at July 15 at 4:08 PM.
CDC

Are you answering for yourself or someone else?
Are you answering for yourself or someone else?

Bot sent

Myself

Someone else
Sent at July 15 at 4:08 PM5 minutes ago
User You said, Myself . Sent at July 15 at 4:08 PM.
Myself
Myself

Sent at July 15 at 4:08 PM5 minutes ago
Bot CDC said, Do you have any of these life-threatening symptoms? Bluish lips or face Severe and constant pain or pressure in the chest Extreme difficulty breathing (gasping for air or cannot talk without catching your breath) Severe and constant dizziness or lightheadedness Serious disorientation (acting confused) Unconscious or very difficult to wake up Slurred speech (new or worsening) Seizures Signs of low blood pressure (too weak to stand, light headed, feeling cold, pale, clammy skin) . Sent at July 15 at 4:08 PM.
CDC

Do you have any of these life-threatening symptoms? Bluish lips or face Severe and constant pain or pressure in the chest Extreme difficulty breathing (gasping for air or cannot talk without catching your breath) Severe and constant dizziness or lightheadedness Serious disorientation (acting confused) Unconscious or very difficult to wake up Slurred speech (new or worsening) Seizures Signs of low blood pressure (too weak to stand, light headed, feeling cold, pale, clammy skin)
Do you have any of these life-threatening symptoms?

Bluish lips or face

Severe and constant pain or pressure in the chest

Extreme difficulty breathing (gasping for air or cannot talk without catching your breath)

Severe and constant dizziness or lightheadedness

Serious disorientation (acting confused)

Unconscious or very difficult to wake up

Slurred speech (new or worsening)

Seizures

Signs of low blood pressure (too weak to stand, light headed, feeling cold, pale, clammy skin)

Bot sent

Yes

No
Sent at July 15 at 4:08 PM3 minutes ago
User You said, No . Sent at July 15 at 4:08 PM.
No
No

Sent at July 15 at 4:08 PMA minute ago
Bot CDC said, What is your age? . Sent at July 15 at 4:08 PM.
CDC

What is your age?
What is your age?

Bot sent

[Redacted]

Submit
Bot CDC said, Are you feeling ill? . Sent at July 15 at 4:08 PM.
CDC

Are you feeling ill?
Are you feeling ill?

Bot sent

Yes

No
Sent at July 15 at 4:08 PM5 minutes ago
User You said, Yes . Sent at July 15 at 4:08 PM.
Yes
Yes

Sent at July 15 at 4:08 PMA minute ago
Bot CDC said, What is your gender? . Sent at July 15 at 4:08 PM.
CDC

What is your gender?
What is your gender?

Bot sent

Male

Female

Other
Sent at July 15 at 4:08 PMA minute ago
User You said, Male . Sent at July 15 at 4:08 PM.
Male
Male

Sent at July 15 at 4:08 PM3 minutes ago
Bot CDC said, In the two weeks before you felt sick, did you have contact with someone diagnosed with COVID-19? . Sent at July 15 at 4:08 PM.
CDC

In the two weeks before you felt sick, did you have contact with someone diagnosed with COVID-19?
In the two weeks before you felt sick, did you have contact with someone diagnosed with COVID-19?

Bot sent

Yes

No

I don't know
Sent at July 15 at 4:08 PMA minute ago
User You said, Yes . Sent at July 15 at 4:08 PM.
Yes
Yes

Sent at July 15 at 4:08 PMA minute ago
Bot CDC said, Do you have any of the following? (check any) . Sent at July 15 at 4:08 PM.
CDC

Do you have any of the following? (check any)
Do you have any of the following? (check any)

Bot sent

Fever or feeling feverish (chills, sweating)

Cough

Mild or moderate difficulty breathing

Sore throat

Muscle aches or body aches

Vomiting or diarrhea

New loss of taste or smell

Other symptoms

Submit
Bot CDC said, Do you live in a long-term care facility or nursing home? . Sent at July 15 at 4:08 PM.
CDC

Do you live in a long-term care facility or nursing home?
Do you live in a long-term care facility or nursing home?

Bot sent

Yes

No
Sent at July 15 at 4:08 PMA minute ago
User You said, No . Sent at July 15 at 4:08 PM.
No
No

Sent at July 15 at 4:08 PMA minute ago
Bot CDC said, In the last two weeks, have you worked or volunteered in a healthcare facility or as a first responder? Facilities include a hospital, other medical setting, or long-term care facility. . Sent at July 15 at 4:08 PM.
CDC

In the last two weeks, have you worked or volunteered in a healthcare facility or as a first responder? Facilities include a hospital, other medical setting, or long-term care facility.
In the last two weeks, have you worked or volunteered in a healthcare facility or as a first responder? Facilities include a hospital, other medical setting, or long-term care facility.

Bot sent

Yes

No
Sent at July 15 at 4:08 PMA minute ago
User You said, No . Sent at July 15 at 4:08 PM.
No
No

Sent at July 15 at 4:08 PMA minute ago
Bot CDC said, Oops. Something went wrong and we need to start over. . Sent at July 15 at 4:08 PM.
CDC

Oops. Something went wrong and we need to start over.
Oops. Something went wrong and we need to start over.

**Comment by pwhitebe** [comment] 2020-07-15 21:37
Greetings, The localization file we used to import custom messages to the main CDC bot was accidentally filtered, so only some of the updated messages transferred over.  We have since updated the rest of the messages, and the bot is proceeding properly to asking about additional risk factors. 

Thank you for reaching out, please let us know if the issue is not corrected for you, or if you see any other issues.

**Closed** 2020-07-16 12:19 UTC
